stages:
  - build
  - deploy

buildAndTest:
  image: rocker/tidyverse
  stage: build
  script:
    # Install package dependencies
    - R -e 'install.packages(c("ape", "readxl", "writexl"))'
    # Install pkgdown
    - R -e 'install.packages("pkgdown")'
    # Install package
    - make install
    # Build website
    - make pkgdown
  artifacts:
    paths:
      - docs

pages:
  stage: deploy
  script:
    - mv docs public
  artifacts:
    paths:
      - public
