stages:
  - build
  - deploy

buildAndTest:
  image: rocker/tidyverse
  stage: build
  script:
    # Install the qpdf dependency using the Debian `apt-get` package manager
    - apt-get update && apt-get -y install qpdf
    # Install package dependencies
    - R -e 'install.packages(c("ape", "readxl", "writexl", "testthat", "stringdist", "qualV", "igraph"))'
    # Install pkgdown
    - R -e 'install.packages("pkgdown")'
    # Test package
    - make test
    # Install package
    - make install
    # R CMD check
    - make check
    - mkdir -p check
    - cp R-CMD-check_output.txt R-CMD-check_badge.svg check/
    # Build website
    - make pkgdown
    # Copy R CMD check results
    - cp check/* docs/
  artifacts:
    paths:
      - docs

pages:
  stage: deploy
  script:
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master
