### * Description

# This is a Makefile, which can be used with the `make` command from the
# terminal to automatically run some tasks based on rules defined below.

### * Setup

# Get the path to the project top directory (based on where the `.git` folder is located)
TOP_DIR=$(shell git rev-parse --show-toplevel)

### ** Colors

# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-printf-in-linux
# https://siongui.github.io/2016/02/18/makefile-printf-color-output/#id3
RED = "\\033[31m"
GREEN = "\\033[92m"
NC = "\\033[0m"

### * Rules

### ** help

# http://swcarpentry.github.io/make-novice/08-self-doc/
# https://stackoverflow.com/questions/19129485/in-linux-is-there-a-way-to-align-text-on-a-delimiter
.PHONY: help
help: Makefile
	@printf "\n"
	@printf "Please use 'make <target>' where <target> is one of\n"
	@printf "\n"
	@sed -n 's/^## /    /p' $< | column -t -s ":"

### ** document

## document : generate package documentation using Roxygen
.PHONY: document
document:
	@printf "\n"
	@printf "$(GREEN)*** Generating package documentation with Roxygen ***$(NC)\n"
	@printf "\n"
	@ Rscript -e 'devtools::document()'

### ** install

## install : install the package (also runs "document")
.PHONY: install
install: document
	@printf "\n"
	@printf "$(GREEN)*** Installing the package ***$(NC)\n"
	@printf "\n"
	@ Rscript -e 'devtools::install(upgrade = FALSE)'

### ** pkgdown

## pkgdown : build the package website in docs/ using pkgdown
.PHONY: pkgdown
pkgdown:
	@printf "\n"
	@printf "$(GREEN)*** Building package website with pkgdown ***$(NC)\n"
	@printf "\n"
	@Rscript -e 'pkgdown::build_site()'

### ** check

## check : run R CMD CHECK through devtools check() function
.PHONY: check
check:
	@printf "\n"
	@printf "$(GREEN)*** Running 'devtools::check()' ***$(NC)\n"
	@printf "\n"
	@Rscript .run_check_and_get_badge.R

### ** clean

## clean : delete all files and folders automatically generated
.PHONY: clean
clean: clean-man clean-docs
	@printf "\n"
	@printf "$(GREEN)*** Cleaned automatically generated files and folders ***$(NC)\n"
	@printf "\n"

### ** clean-man

##clean-man : delete documentation generated by Roxygen
.PHONY: clean-man
clean-man:
	rm -f man/*

### ** clean-docs

##clean-docs : delete documentation generated by pkgdown
.PHONY: clean-docs
clean-docs:
	rm -fr docs/*
